
package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVBank", targetNamespace = "http://vbank.hfu.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVBank {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCreditRate", targetNamespace = "http://vbank.hfu.de/", className = "com.test.GetCreditRate")
    @ResponseWrapper(localName = "getCreditRateResponse", targetNamespace = "http://vbank.hfu.de/", className = "com.test.GetCreditRateResponse")
    public Double getCreditRate(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
