
package de.hfu.vbank.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.0
 * Sat Dec 17 15:57:21 CET 2011
 * Generated source version: 2.5.0
 */

@XmlRootElement(name = "getCreditRateResponse", namespace = "http://vbank.hfu.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCreditRateResponse", namespace = "http://vbank.hfu.de/")

public class GetCreditRateResponse {

    @XmlElement(name = "return")
    private java.lang.Double _return;

    public java.lang.Double getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.Double new_return)  {
        this._return = new_return;
    }

}

