
package de.hfu.vbank.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.0
 * Sat Dec 17 15:57:21 CET 2011
 * Generated source version: 2.5.0
 */

@XmlRootElement(name = "getCreditRate", namespace = "http://vbank.hfu.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCreditRate", namespace = "http://vbank.hfu.de/", propOrder = {"arg0", "arg1", "arg2"})

public class GetCreditRate {

    @XmlElement(name = "arg0")
    private double arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private java.lang.String arg2;

    public double getArg0() {
        return this.arg0;
    }

    public void setArg0(double newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public java.lang.String getArg2() {
        return this.arg2;
    }

    public void setArg2(java.lang.String newArg2)  {
        this.arg2 = newArg2;
    }

}

