
package de.hfu.vschufa.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.0
 * Sat Dec 17 15:52:38 CET 2011
 * Generated source version: 2.5.0
 */

@XmlRootElement(name = "getScoreValue", namespace = "http://vschufa.hfu.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getScoreValue", namespace = "http://vschufa.hfu.de/")

public class GetScoreValue {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

