
package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVSchufa", targetNamespace = "http://vschufa.hfu.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVSchufa {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getScoreValue", targetNamespace = "http://vschufa.hfu.de/", className = "com.test.GetScoreValue")
    @ResponseWrapper(localName = "getScoreValueResponse", targetNamespace = "http://vschufa.hfu.de/", className = "com.test.GetScoreValueResponse")
    public int getScoreValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
