
package com.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VSchufaService", targetNamespace = "http://vschufa.hfu.de/", wsdlLocation = "http://localhost:8080/VSchufaService/services/VSchufaPort?wsdl")
public class VSchufaService
    extends Service
{

    private final static URL VSCHUFASERVICE_WSDL_LOCATION;
    private final static WebServiceException VSCHUFASERVICE_EXCEPTION;
    private final static QName VSCHUFASERVICE_QNAME = new QName("http://vschufa.hfu.de/", "VSchufaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/VSchufaService/services/VSchufaPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VSCHUFASERVICE_WSDL_LOCATION = url;
        VSCHUFASERVICE_EXCEPTION = e;
    }

    public VSchufaService() {
        super(__getWsdlLocation(), VSCHUFASERVICE_QNAME);
    }

    public VSchufaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VSCHUFASERVICE_QNAME, features);
    }

    public VSchufaService(URL wsdlLocation) {
        super(wsdlLocation, VSCHUFASERVICE_QNAME);
    }

    public VSchufaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VSCHUFASERVICE_QNAME, features);
    }

    public VSchufaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VSchufaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVSchufa
     */
    @WebEndpoint(name = "VSchufaPort")
    public IVSchufa getVSchufaPort() {
        return super.getPort(new QName("http://vschufa.hfu.de/", "VSchufaPort"), IVSchufa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVSchufa
     */
    @WebEndpoint(name = "VSchufaPort")
    public IVSchufa getVSchufaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vschufa.hfu.de/", "VSchufaPort"), IVSchufa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VSCHUFASERVICE_EXCEPTION!= null) {
            throw VSCHUFASERVICE_EXCEPTION;
        }
        return VSCHUFASERVICE_WSDL_LOCATION;
    }

}
